from __future__ import annotations

import os
import random
import uuid
from datetime import datetime, timedelta
from pathlib import Path

import oracledb  # type: ignore[import-not-found]
from dotenv import load_dotenv
from passlib.context import CryptContext

ROOT_DIR = Path(__file__).resolve().parents[2]
load_dotenv(ROOT_DIR / ".env")

DB_USER = os.environ["DB_USER"]
DB_PASSWORD = os.environ["DB_PASSWORD"]
DB_DSN = os.environ["DB_DSN"]
WALLET_PATH = os.environ.get("WALLET_PATH") or os.environ.get("WALLET_LOCATION")
WALLET_PASSWORD = os.environ.get("WALLET_PASSWORD", "")

if not WALLET_PATH:
    raise RuntimeError("WALLET_PATH no definido en .env")

wallet_location = Path(WALLET_PATH)
if not wallet_location.is_absolute():
    wallet_location = (ROOT_DIR / wallet_location).resolve()

pwd_context = CryptContext(schemes=["pbkdf2_sha256"], deprecated="auto")


def get_connection():
    return oracledb.connect(
        user=DB_USER,
        password=DB_PASSWORD,
        dsn=DB_DSN,
        config_dir=str(wallet_location),
        wallet_location=str(wallet_location),
        wallet_password=WALLET_PASSWORD,
    )


def fetch_products(cursor):
    cursor.execute(
        "SELECT column_name FROM user_tab_columns WHERE table_name = 'PRODUCTOS'"
    )
    available_columns = {row[0].lower() for row in cursor.fetchall()}
    select_columns = ["id_producto", "nombre", "precio_actual", "stock"]
    if "marca" in available_columns:
        select_columns.append("marca")
    if "categoria" in available_columns:
        select_columns.append("categoria")
    if "precio_fabricacion" in available_columns:
        select_columns.append("precio_fabricacion")
    cursor.execute(
        f"SELECT {', '.join(select_columns)} FROM productos ORDER BY nombre"
    )
    rows = cursor.fetchall()
    return [dict(zip(select_columns, row)) for row in rows]


def fetch_vendors(cursor):
    cursor.execute(
        "SELECT v.id_vendedor, u.nombre, v.codigo_vendedor FROM vendedores v JOIN usuarios u ON u.id_usuario = v.id_vendedor ORDER BY v.codigo_vendedor"
    )
    return cursor.fetchall()


def fetch_clients(cursor):
    cursor.execute(
        "SELECT id_usuario, nombre FROM usuarios WHERE tipo_usuario = 'Cliente' ORDER BY nombre"
    )
    return cursor.fetchall()


def execute_ddl(cursor, statement: str):
    cursor.execute(
        f"""
        BEGIN
          EXECUTE IMMEDIATE q'[ {statement} ]';
        EXCEPTION
          WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
              RAISE;
            END IF;
        END;
        """
    )


def ensure_client_tables(cursor):
    execute_ddl(
        cursor,
        """
        CREATE TABLE vendedores (
            id_vendedor         VARCHAR2(36) NOT NULL,
            codigo_vendedor     VARCHAR2(20) NOT NULL,
            especialidad        VARCHAR2(120),
            objetivo_ventas     NUMBER(10, 2) DEFAULT 0,
            fecha_alta          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_vendedores PRIMARY KEY (id_vendedor),
            CONSTRAINT uq_vendedores_codigo UNIQUE (codigo_vendedor),
            CONSTRAINT fk_vendedores_usuario FOREIGN KEY (id_vendedor)
                REFERENCES usuarios (id_usuario)
                ON DELETE CASCADE
        )
        """,
    )
    execute_ddl(
        cursor,
        """
        CREATE TABLE producto_vendedor (
            id_producto         VARCHAR2(20) NOT NULL,
            id_vendedor         VARCHAR2(36) NOT NULL,
            fecha_asignacion     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_producto_vendedor PRIMARY KEY (id_producto),
            CONSTRAINT fk_pv_producto FOREIGN KEY (id_producto)
                REFERENCES productos (id_producto)
                ON DELETE CASCADE,
            CONSTRAINT fk_pv_vendedor FOREIGN KEY (id_vendedor)
                REFERENCES vendedores (id_vendedor)
                ON DELETE CASCADE
        )
        """,
    )
    execute_ddl(
        cursor,
        """
        CREATE TABLE competencia_mercado (
            id_competencia              NUMBER GENERATED BY DEFAULT AS IDENTITY,
            id_producto                 VARCHAR2(20) NOT NULL,
            fecha                       DATE DEFAULT CURRENT_DATE NOT NULL,
            precio_competencia_promedio  NUMBER(10, 2) NOT NULL,
            fuente                      VARCHAR2(150),
            CONSTRAINT pk_competencia_mercado PRIMARY KEY (id_competencia),
            CONSTRAINT fk_competencia_producto FOREIGN KEY (id_producto)
                REFERENCES productos (id_producto)
                ON DELETE CASCADE,
            CONSTRAINT chk_competencia_precio CHECK (precio_competencia_promedio >= 0)
        )
        """,
    )
    execute_ddl(
        cursor,
        """
        CREATE TABLE ventas (
            id_venta        VARCHAR2(36) NOT NULL,
            id_cliente      VARCHAR2(36) NOT NULL,
            id_vendedor     VARCHAR2(36),
            fecha_venta     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            monto_total     NUMBER(12, 2) NOT NULL,
            total_unidades  NUMBER(10) NOT NULL,
            CONSTRAINT pk_ventas PRIMARY KEY (id_venta),
            CONSTRAINT fk_ventas_cliente FOREIGN KEY (id_cliente)
                REFERENCES usuarios (id_usuario),
            CONSTRAINT fk_ventas_vendedor FOREIGN KEY (id_vendedor)
                REFERENCES vendedores (id_vendedor)
                ON DELETE SET NULL,
            CONSTRAINT chk_ventas_monto CHECK (monto_total >= 0),
            CONSTRAINT chk_ventas_unidades CHECK (total_unidades >= 0)
        )
        """,
    )
    execute_ddl(
        cursor,
        """
        CREATE TABLE venta_detalle (
            id_venta         VARCHAR2(36) NOT NULL,
            id_producto      VARCHAR2(20) NOT NULL,
            cantidad         NUMBER(10) NOT NULL,
            precio_unitario  NUMBER(10, 2) NOT NULL,
            costo_unitario   NUMBER(10, 2),
            subtotal         NUMBER(12, 2) NOT NULL,
            margen_unitario  NUMBER(10, 2),
            CONSTRAINT pk_venta_detalle PRIMARY KEY (id_venta, id_producto),
            CONSTRAINT fk_detalle_venta FOREIGN KEY (id_venta)
                REFERENCES ventas (id_venta)
                ON DELETE CASCADE,
            CONSTRAINT fk_detalle_producto FOREIGN KEY (id_producto)
                REFERENCES productos (id_producto),
            CONSTRAINT chk_detalle_cantidad CHECK (cantidad > 0),
            CONSTRAINT chk_detalle_precio CHECK (precio_unitario >= 0),
            CONSTRAINT chk_detalle_subtotal CHECK (subtotal >= 0)
        )
        """,
    )


def ensure_product_columns(cursor):
    for statement in [
        "ALTER TABLE productos ADD (marca VARCHAR2(150))",
        "ALTER TABLE productos ADD (stock NUMBER(10) DEFAULT 0 NOT NULL)",
        "ALTER TABLE productos ADD (precio_fabricacion NUMBER(10, 2))",
        "ALTER TABLE productos ADD (fecha_caducidad DATE)",
    ]:
        cursor.execute(
            f"""
            BEGIN
                EXECUTE IMMEDIATE q'[ {statement} ]';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -1430 THEN
                        RAISE;
                    END IF;
            END;
            """
        )


def backfill_inventory(cursor):
    products = fetch_products(cursor)
    for product in products:
        stock_value = int(product.get("stock") or 0)
        price_value = float(product.get("precio_actual") or 0)
        cost_value = product.get("precio_fabricacion")

        next_stock = stock_value if stock_value > 0 else random.randint(18, 80)
        next_cost = (
            float(cost_value)
            if cost_value is not None
            else round(max(price_value * random.uniform(0.62, 0.88), 1.0), 2)
        )

        cursor.execute(
            "UPDATE productos SET stock = :stock, precio_fabricacion = :precio_fabricacion, fecha_actualizacion = CURRENT_TIMESTAMP "
            "WHERE id_producto = :id_producto",
            {
                "stock": next_stock,
                "precio_fabricacion": next_cost,
                "id_producto": product["id_producto"],
            },
        )


def ensure_users(cursor, prefix: str, count: int, tipo_usuario: str, name_prefix: str):
    existing_ids = set()
    cursor.execute(
        "SELECT correo FROM usuarios WHERE correo LIKE :pattern",
        {"pattern": f"{prefix}%@demo.local"},
    )
    for (correo,) in cursor.fetchall():
        existing_ids.add(correo)

    generated = []
    for index in range(1, count + 1):
        correo = f"{prefix}{index:02d}@demo.local"
        if correo in existing_ids:
            continue
        user_id = str(uuid.uuid4())
        cursor.execute(
            "INSERT INTO usuarios (id_usuario, nombre, telefono, correo, tipo_usuario, password_hash) "
            "VALUES (:id_usuario, :nombre, :telefono, :correo, :tipo_usuario, :password_hash)",
            {
                "id_usuario": user_id,
                "nombre": f"{name_prefix} {index:02d}",
                "telefono": f"55{index:04d}{index:04d}"[:10],
                "correo": correo,
                "tipo_usuario": tipo_usuario,
                "password_hash": pwd_context.hash("Demo1234"),
            },
        )
        generated.append((user_id, index))
    return generated


def ensure_vendors(cursor, vendor_rows):
    existing = set()
    cursor.execute("SELECT id_vendedor FROM vendedores")
    for (id_vendedor,) in cursor.fetchall():
        existing.add(id_vendedor)

    for vendor_id, index in vendor_rows:
        if vendor_id in existing:
            continue
        cursor.execute(
            "INSERT INTO vendedores (id_vendedor, codigo_vendedor, especialidad, objetivo_ventas) "
            "VALUES (:id_vendedor, :codigo_vendedor, :especialidad, :objetivo_ventas)",
            {
                "id_vendedor": vendor_id,
                "codigo_vendedor": f"V-{2000 + index}",
                "especialidad": random.choice(["Bebidas", "Despensa", "Tecnologia", "Hogar", "Belleza"]),
                "objetivo_ventas": random.randint(80000, 200000),
            },
        )


def assign_products_to_vendors(cursor, vendor_rows):
    cursor.execute("DELETE FROM producto_vendedor")
    products = fetch_products(cursor)
    if not products or not vendor_rows:
        return 0

    assigned = 0
    for index, product in enumerate(products):
        vendor_id = vendor_rows[index % len(vendor_rows)][0]
        cursor.execute(
            "INSERT INTO producto_vendedor (id_producto, id_vendedor) VALUES (:id_producto, :id_vendedor)",
            {"id_producto": product["id_producto"], "id_vendedor": vendor_id},
        )
        assigned += 1
    return assigned


def seed_competition(cursor):
    cursor.execute("SELECT COUNT(*) FROM competencia_mercado")
    if int(cursor.fetchone()[0] or 0) > 0:
        return 0

    cursor.execute("SELECT id_producto, precio_actual FROM productos ORDER BY nombre")
    products = cursor.fetchall()
    total = 0
    for product_id, current_price in products:
        base_price = float(current_price or 0)
        for day_offset in (5, 12, 19):
            variation = random.uniform(0.92, 1.08)
            cursor.execute(
                "INSERT INTO competencia_mercado (id_producto, fecha, precio_competencia_promedio, fuente) "
                "VALUES (:id_producto, :fecha, :precio_competencia_promedio, :fuente)",
                {
                    "id_producto": product_id,
                    "fecha": datetime.utcnow().date() - timedelta(days=day_offset),
                    "precio_competencia_promedio": round(base_price * variation, 2),
                    "fuente": random.choice(["Amazon", "MercadoLibre", "Retail local"]),
                },
            )
            total += 1
    return total


def seed_sales(cursor, client_rows):
    cursor.execute("SELECT COUNT(*) FROM ventas")
    if int(cursor.fetchone()[0] or 0) > 0:
        return 0

    products = [product for product in fetch_products(cursor) if int(product.get("stock") or 0) > 5]
    if not products:
        return 0

    created_sales = 0
    for client_id, _ in client_rows:
        for _ in range(random.randint(1, 2)):
            sale_id = str(uuid.uuid4())
            items = random.sample(products, k=min(random.randint(1, 3), len(products)))
            total_amount = 0.0
            total_units = 0
            cursor.execute(
                "SELECT id_vendedor FROM producto_vendedor WHERE id_producto = :id_producto",
                {"id_producto": items[0]["id_producto"]},
            )
            vendor_row = cursor.fetchone()
            sale_vendor = vendor_row[0] if vendor_row else None

            # insertar primero la cabecera de la venta para respetar la FK
            cursor.execute(
                "INSERT INTO ventas (id_venta, id_cliente, id_vendedor, monto_total, total_unidades) "
                "VALUES (:id_venta, :id_cliente, :id_vendedor, :monto_total, :total_unidades)",
                {
                    "id_venta": sale_id,
                    "id_cliente": client_id,
                    "id_vendedor": sale_vendor,
                    "monto_total": 0,
                    "total_unidades": 0,
                },
            )

            for item in items:
                product_id = item["id_producto"]
                current_price = float(item.get("precio_actual") or 0)
                stock = int(item.get("stock") or 0)
                cost_price = item.get("precio_fabricacion")
                product_name = item.get("nombre")
                product_brand = item.get("marca")

                quantity = random.randint(1, min(5, stock - 1))
                subtotal = round(current_price * quantity, 2)
                total_amount += subtotal
                total_units += quantity
                cursor.execute(
                    "UPDATE productos SET stock = stock - :cantidad, fecha_actualizacion = CURRENT_TIMESTAMP "
                    "WHERE id_producto = :id_producto",
                    {"cantidad": quantity, "id_producto": product_id},
                )
                cursor.execute(
                    "INSERT INTO venta_detalle (id_venta, id_producto, cantidad, precio_unitario, costo_unitario, subtotal, margen_unitario) "
                    "VALUES (:id_venta, :id_producto, :cantidad, :precio_unitario, :costo_unitario, :subtotal, :margen_unitario)",
                    {
                        "id_venta": sale_id,
                        "id_producto": product_id,
                        "cantidad": quantity,
                        "precio_unitario": current_price,
                        "costo_unitario": float(cost_price) if cost_price is not None else None,
                        "subtotal": subtotal,
                        "margen_unitario": round(current_price - float(cost_price), 2) if cost_price is not None else None,
                    },
                )

            # actualizar la cabecera con los totales reales
            cursor.execute(
                "UPDATE ventas SET monto_total = :monto_total, total_unidades = :total_unidades WHERE id_venta = :id_venta",
                {"monto_total": round(total_amount, 2), "total_unidades": total_units, "id_venta": sale_id},
            )
            created_sales += 1

    return created_sales


def main():
    with get_connection() as connection:
        with connection.cursor() as cursor:
            ensure_product_columns(cursor)
            ensure_client_tables(cursor)
            backfill_inventory(cursor)
            vendor_rows = ensure_users(cursor, "vendedor_demo_", 16, "Vendedor", "Vendedor Demo")
            client_rows = ensure_users(cursor, "cliente_demo_", 10, "Cliente", "Cliente Demo")
            ensure_vendors(cursor, vendor_rows)
            all_vendors = fetch_vendors(cursor)
            all_clients = fetch_clients(cursor)
            assigned = assign_products_to_vendors(cursor, all_vendors)
            competition_rows = seed_competition(cursor)
            sales_created = seed_sales(cursor, all_clients)
            connection.commit()

    print(
        "Seed demo completado: "
        f"{len(vendor_rows)} vendedores nuevos, "
        f"{len(client_rows)} clientes nuevos, "
        f"{assigned} productos asignados, "
        f"{competition_rows} registros de competencia, "
        f"{sales_created} ventas demo."
    )


if __name__ == "__main__":
    main()
